token:
  expiration_time: 864000000
  # secret: native_secret_default_12345678901234567890123456789012345678901234567890
  secret: '{cipher}AYAeHdF0IuRBAcvqY3sH99NbmQfBoRG3u05jhZWlflDRqBeSlXLqIXlxUgTArW++kmOW/830J5dEpg71g5ZVVWshQTeTNEQjZDDMKR8UqeNPeO+uUnnTGA/jG2SQj5/0/SeaB06C+fstZIytZxM+zWgnQ4afu0cjMbKZ7ry/66UKf/9wEN952c2JZRlzcyFx5oXJP3cIFKC0EFs58WX2dkBOCoQdiOaBmWwk2pgZe3FVQh8s0Ig5dfJM+uhq668PjFfzAeH30OvPCKaHMvpznLFLkVx8fP7SJzxXFvfZd5nCrhl38XisQxSD3gm3PIuSuMg7Z4hoHI4JJcVi0oFGe0TEu5YjTTIbB0FWhUh/Oz5zxp25BRClSBbzcaT1FiDdedPDV39B/E7LfV+tu+IkoJmR8Rihr5XfWf2BJBlmaV6oc8vY7mNg4ZJKil8BQupCVEfNxx7zVHIfZPhfEtcLT9nlKd1jnj9WpyFZ8ZKdjQPEzrVcDBNbr0QC7bGemAm2Gkrnj0F0lby5/f7TLaH+aXpfRc2X2miIJT3bcB4BHi3uVyCjPtppHnF8Ohvs7JXfAwRDmt8q995on9nYus9u9bi22Fd+2VfIz9rF3OCQV3MMReOKjwszn5gkuLRkBpWaHhA='
gateway: 
  ip: 127.0.0.1
