spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test_user
    # 대칭키
    # password: '{cipher}35edcb5912d52b47946a2995cf66f06da22fb4642fb7a3ec6a7cee3a5e19dcf7'
    # 비대칭키
    password: '{cipher}AYB5rzhZ+9NG+GxrfX6NvzOz37QT4RQARjZqovrs85rdI00MkbVYnoMyKlZMHMrK4bnZcsi+jPKPlD06476hJPCiU6XLO89ldhhflrqcTFwrYeQBH8fT4u/NXOyLW/necPAz4QFeELegaJeeuPqQYqhui52om83muFjlaCBxY7JuhxUdpoo+f5t52Wr331z4bpkkrzuTuWr/lS8Uo+cZR41t7NvEBEaHpS5YmBWKic5AP7zmR2h7uHSHISK9l3XyGZV9Yb6gZQJGJi6zHlU6cMmaKjKymASErI9E3fb4zlHCxsC5lUen3pJcBSK6HCD8n05kY3TCFWUvX+N9zkvl6fmYpvQDbm3x3fq/2cf+fxoo17RQfdNdDdNKurUBc+XV83E8VdySgrWETEWDLO5vfhlncrLB1+R3kyWWfdsEYRgA4N2YeNAVeUA7NVbg/6png9vGIPw1KDWd5bA60auBVy4qEjlrjxZfsklZ0FEhT7YvUS3dmNYfy4EdXxQS42DIMSeX+/IA7t0kJg3mc4pNEd11e7oFiuj1TP6esPDbz5e1hw=='
    driver-class-name: com.mysql.cj.jdbc.Driver