spring:
  datasource:
    url: jdbc:mysql://mysql:33306/testdb
    username: test_user
    # 대칭키
    # password: '{cipher}35edcb5912d52b47946a2995cf66f06da22fb4642fb7a3ec6a7cee3a5e19dcf7'
    # 비대칭키
    password: '{cipher}AYCsJ3G7v6wo/kM/buFDLSa0c7KAN1rQ+khCBAkP0fSp22eGIA/hZt3+RB+6C6nF8Gh+9pk4HRlIBcaVB3jS2Li7HlWe7J+ejh67EeE0WqzRajpUICoMeOIs2wvcznmZJ4ntkP7wLnWDeQmfxX7h7/H3hqJjvZwXgGCzOr6dF+3CosEQVdqPCXxRfe+EtOk8pMyR9txTv6KvaFN384AA15VXZFrPFh5ZRoD1hzUc76OGz8y68dJL9OUquR78lIKh7FZzGOdP4vjjw2jYH57OfRUaWvUC8MCSUE4CyzUl630Pt13h5uCKIYf51Xfy7YOLR5ltOEh3O6Kljuu493VIuwmyQHVLPzs4oP0zWG5ZfjoGJOlpB55Y6OFh0pn8VvMWghZjxKmFePHK8RT//NFIR47Io6Ix8KOjiRkMyd4eC8yFXLR5KacdJxyMMclPqnE9sLs0Q9AyMiMAPWFT1WCBa5lzio0lrEnDDQedgaga4M77wbAQmbQKKKOQBqKSww59hgj+QCOtawWccWKDPLgUvMZJcHdaRK3/yW/1hRD5HFBe+A=='
    driver-class-name: com.mysql.cj.jdbc.Driver
gateway:
  ip: 172.18.0.5

order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders
  # main에 @LoadBalced  추가해야 사용가능 (Euraka에 등록된 서비스명)
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
